Switch to union query to make XC happy.
It complains about the VALUES syntax with this error:

    ERROR:  unexpected varno 6 in JOIN RTE 5

NFI what that means, or why it doesn't like it, but I've reported it
to the XC folks.  Hopefully can find a better fix and ignore this
change.